<?php
/**
 * Copyright (c) 2013-2016 Radial Commerce, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2016 Radial Commerce, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, array('_secure'=>true))."radial_creditcard/".Mage::getStoreConfig('radial_creditcard/braintree_filename'); ?>" integrity="<?php $hash = base64_encode(hash('sha512', file_get_contents(Mage::getBaseDir().'/js/radial_creditcard/'.Mage::getStoreConfig('radial_creditcard/braintree_filename')), true)); $hash256 = base64_encode(hash('sha256', file_get_contents(Mage::getBaseDir().'/js/radial_creditcard/'.Mage::getStoreConfig('radial_creditcard/braintree_filename')), true)); echo 'sha512-'.$hash.' sha256-'.$hash256; ?>" crossorigin="anonymous"></script>
